name: null
favicon: null
layout_spectrum: 0.20825492544099689
typography_spectrum: 0.2802085648290813
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4322831714525819
  lightness: 0.9320096166338772
  saturation: 0.30409279302693903
  rhythmicContrast: 0.13278305204585195
purpose: []
